### ISSUE TITLE
expected devel but got groovy

### ISSUE THREAD

**Issue by troyBORG** [wimpysworld/rolling-rhino#17]
```
W: Conflicting distribution: http://security.ubuntu.com/ubuntu devel-security InRelease (expected devel-security but got groovy)

W: Conflicting distribution: http://archive.ubuntu.com/ubuntu devel InRelease (expected devel but got groovy)

W: Conflicting distribution: http://archive.ubuntu.com/ubuntu devel-updates InRelease (expected devel-updates but got groovy)

W: Conflicting distribution: http://archive.ubuntu.com/ubuntu devel-backports InRelease (expected devel-backports but got groovy)
```

I noticed this, unsure if its a bug.

**Comment by basak** [comment]
This is https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1728616

**Comment by m-ueberall** [comment]
For the record, I've cloned an existing LXD container (based on Focal Fossa/20.04LTS), bypassed the warnings and ended up with the above. Despite the hundreds of initial updates, this effectively does not allow me to upgrade to QEmu 5.0 …

**Comment by flexiondotorg** [comment]
Qemu is currently 4.2 in groovy/devel. Are you getting `qemu` from a PPA?

**Comment by davidkrauser** [comment]
I'm seeing the same warning, but it isn't a breaking warning for me. Updates, upgrades, and package installation still seems to work fine.

@m-ueberall It looks like QEMU 5.0 is in the proposed pocket right now for devel/groovy, so it isn't available for users, yet:
```
$ rmadison qemu | grep groovy
 qemu | 1:4.2-3ubuntu9          | groovy                    | source, amd64, arm64, armhf, ppc64el, riscv64, s390x
 qemu | 1:5.0-5ubuntu2          | groovy-proposed           | source, amd64, arm64, armhf, ppc64el, riscv64, s390x
```
Maybe you were expecting rolling rhino to also enable getting proposed packages by default?

**Comment by m-ueberall** [comment]
> Qemu is currently 4.2 in groovy/devel. Are you getting `qemu` from a PPA?

My bad, I misread the [overview on Launchpad](https://launchpad.net/ubuntu/+source/qemu), should have looked at [groovy-proposed](http://ftp.fbi.h-da.de/ubuntu/ubuntu/dists/groovy-proposed/).

**Comment by troyBORG** [comment]
I guess i was wondering if there was a way to squelch the warnings?

**Comment by p4j0c4** [comment]
I looked for a solution to overcome that the errors were not shown to all users.

The workaround can be done by creating the following aliases, which I created with the following file name:

_**`/etc/profile.d/00-apt-update-conflicting-distribution-patch.sh`**_
```
   alias sudo='sudo '
   alias apt='apt '
   alias update='update 2> /dev/null'
```
**Comments:**

   [+] Take into account the **`spaces`** at the end of the first two aliases.
   [+] Run the command **`chmod +x`** 'file name' so that it becomes executable.
   [+] The file name can be any name but must start with **`00-*`** to be the first file to be read at startup.

The same result can be obtained for a single user using the file _**`~/.bash_aliases`**._

I wish I would have found a better strategy, but with this patch at least the errors of the apt update are not shown.
